crop/urls.py
from django.urls import path
from .views import PostUpdateView, UserPostListView
from . import views
import re

app_name = 'crop'
urlpatterns = [
    path('', views.home, name='home'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', views.post_detail, name='post-detail'),
    path('post/new/', views.post_create, name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', views.post_delete, name='post-delete'),
    path('buy/<int:pk>/', views.buy, name='buy'),
]

farmerportal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from django.contrib.auth import views as auth_views

admin.site.site_header = "FARMERS PORTAL"
admin.site.site_title = "FARMERS PORTAL"
admin.site.index_title = "Welcome to Farmers Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('crop/', include('crop.urls', namespace='crop')),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.profile, name='profile'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crop/models.py
from django.db import models
from PIL import Image
from django.contrib.auth.models import User
from django.utils import timezone

class Category(models.Model):
	name = models.CharField(max_length=200)

	def __str__(self):
		return self.name

class Types(models.Model):
	name = models.CharField(max_length=200)

	def __str__(self):
		return self.name

class Unit(models.Model):
	name = models.CharField(max_length=100)
	value = models.IntegerField()

	def __str__(self):
		return self.name

class Crop(models.Model):
	farmer = models.OneToOneField(User, on_delete=models.CASCADE)
	cat = models.ForeignKey('Category', on_delete=models.CASCADE)
	name = models.ForeignKey('Types', on_delete=models.CASCADE)
	quantity = models.IntegerField()
	unit = models.ForeignKey('Unit', on_delete=models.CASCADE)
	description = models.TextField(null=True, blank=True)
	pickup = models.CharField(max_length=200)
	image = models.ImageField(upload_to='crop', null=True, blank=True)
	date_posted = models.DateField(default=timezone.now)
	price = models.IntegerField(default=0)
	owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='owner', null=True, blank=True, default = None)

	def __str__(self):
		return f'{self.farmer} - {self.date_posted}'

	def get_absolute_url(self):
		return reverse('post-detail', kwargs={'pk': self.pk})


class Bid(models.Model):
	author = models.ForeignKey(User, on_delete=models.CASCADE, default = None)
	value = models.CharField(max_length=10, default = None)
	stuff = models.ForeignKey(Crop, on_delete=models.CASCADE, default = None)

	def __str__(self):
		return f'{self.stuff.name}-{self.author.username}'

class Transaction(models.Model):
	farmer = models.OneToOneField(User, on_delete=models.CASCADE, related_name='farmer')
	buyer = models.OneToOneField(User, on_delete=models.CASCADE, related_name='buyer')

	def __str__(self):
		return f'{self.farmer.user.username} - {self.buyer.user.username}'

class Newsletter(models.Model):
	mail = models.EmailField()

	def __str__(self):
		return self.mail

crop/forms.py
from django import forms
from .models import Crop, Bid

class CropForm(forms.ModelForm):
	class Meta:
		model = Crop
		fields = ('cat', 'name', 'quantity', 'unit', 'description', 'pickup', 'image')

class BidForm(forms.ModelForm):
	class Meta:
		model = Bid
		fields = ['value',]

crop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from .models import Crop, Category, Types
from .forms import CropForm, BidForm
from django.urls import reverse, reverse_lazy
from django import forms
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
import datetime
from django.utils import timezone

@login_required
def post_create(request):
    form = CropForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.farmer = request.user
        instance.save()
        form.save_m2m()
        return redirect('crop:home')
    context = {
        "form": form,
    }
    return render(request, "crop/post_form.html", context)

class UserPostListView(ListView):
    model = Crop
    template_name = 'crop/user_posts.html'
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Crop.objects.filter(farmer=user).order_by('-date_posted')

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Crop
    fields = ('farmer', 'cat', 'name', 'quantity', 'unit', 'description', 'pickup', 'image')
    success_url = reverse_lazy('crop:home')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.farmer:
            return True
        return False

@login_required
def post_delete(request, pk):
    crop = get_object_or_404(Crop, pk=pk)
    crop.delete()
    return redirect('crop:home')

def buy(request, pk):
    object = get_object_or_404(Post, pk=pk)
    object.owner = request.user
    object.save()
    return redirect('core:post-detail', pk) 

def post_detail(request, pk):
    object = get_object_or_404(Crop, pk=pk)
    now = timezone.now()
    bids = Crop.objects.all()
    bids = bids.filter(stuff=object)
    highest = (None,None)
    if bids:
        high = {}
        for i in bids:
            high[int(i.value)]=i.author
        sorted_d = sorted(high.items(), key=operator.itemgetter(0),reverse=True)
        highest = sorted_d[0]
    form = BidForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.author = request.user
        instance.stuff = object
        instance.save()
        form.save_m2m()
        return redirect('crop:post-detail', pk)
    context = {
        "form": form,
        "now": now,
        "object": object,
        "highest": highest[0],
        "bidder": str(highest[1]),
        }

def home(request):
    posts = Crop.objects.all()
    posts = posts[::-1]
    recent_posts = posts[:4]
    context = {
        'posts': posts,
        'recent_posts': recent_posts,
    }
    return render(request, 'crop/home.html', context)

crop/templates/crop/base.html
{% load static %}
    <!doctype html>
    <html lang="en">

    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="icon" href="{% static 'crop/img/logo.png' %}" type="image/png">
      <title>FARHUB</title>
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static 'crop/css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'crop/vendors/linericon/style.css' %}">
        <link rel="stylesheet" href="{% static 'crop/css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'crop/vendors/owl-carousel/owl.carousel.min.css' %}">
        <link rel="stylesheet" href="{% static 'crop/vendors/lightbox/simpleLightbox.css' %}">
        <link rel="stylesheet" href="{% static 'crop/vendors/nice-select/css/nice-select.css' %}">
        <link rel="stylesheet" href="{% static 'crop/vendors/animate-css/animate.css' %}">
        <link rel="stylesheet" href="{% static 'crop/vendors/jquery-ui/jquery-ui.css' %}">
        <!-- main css -->
        <link rel="stylesheet" href="{% static 'crop/css/style.css' %}">
        <link rel="stylesheet" href="{% static 'crop/css/responsive.css' %}">
    </head>

    <body>

        <!--================Header Menu Area =================-->
        <header class="header_area">
            
            <div class="main_menu">
                <nav class="navbar navbar-expand-lg navbar-light">
                    <div class="container-fluid">
                        <a class="navbar-brand logo_h" href="{% url 'crop:home' %}">
                            <img class="logo" src="{% static 'crop/img/logo.png' %}" alt="" style="height: 75px; width: 75px;">
                        </a>
                        <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                            <div class="row w-100">
                                <div class="col-lg-7 pr-0">
                                    <ul class="nav navbar-nav center_nav pull-right">
                                        {% if user.is_authenticated %}
                                        <li class="nav-item">
                                            <a class="nav-link" href="{% url 'profile' %}">Profile</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                                        </li>
                                        {% else %}
                                        <li class="nav-item">
                                            <a class="nav-link" href="{% url 'register' %}">Register</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="{% url 'login' %}">Login</a>
                                        </li>
                                        
                                        {% endif %}
                                        <ul class="nav navbar-nav center_nav pull-right">
                                        <li class="nav-item">
                                            <a class="nav-link" href="{% url 'crop:home' %}">Buy</a>
                                        </li>
                                        
                                      <li class="nav-item">
                                            <a class="nav-link" href="{% url 'crop:post-create' %}">Sell</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="">Contact Us</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </nav>
            </div>
        </header>
        <!--================Header Menu Area =================-->

        <!--================Home Banner Area =================-->
        <!--<section class="home_banner_area">
            <div class="overlay"></div>
            <div class="banner_inner d-flex align-items-center">
                <div class="container">
                    <div class="banner_content row">
                        <div class="offset-lg-2 col-lg-8">
                            <h2>FARMER'S HUB</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna
                                aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--================End Home Banner Area =================-->

<br><br><br><br>
<div class="container">
        <h1></h1>
        <section id="main">
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
        <div class="">
          {% block content %}{% endblock %}
        </div>
    </section>
        
      </div>
      <!--<section class="subscription-area section_gap">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8">
                        <div class="section-title text-center">
                            <h2>Subscribe for Our Newsletter</h2>
                            <span>We won’t send any kind of spam</span>
                        </div>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-lg-6">
                        <div id="mc_embed_signup">
                            <form class="subscription relative">
                                <input type="email" name="EMAIL" placeholder="Email address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email address'"
                                 required="">
                                <button type="submit" class="newsl-btn">Get Started</button>
                                <div class="info"></div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>-->
        <!--================ End Subscription Area ================-->

        <!--================ start footer Area  =================-->
        <footer class="footer-area section_gap">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3  col-md-6 col-sm-6">
                        <div class="single-footer-widget">
                            <h6 class="footer_title">About Us</h6>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore dolore magna aliqua.</p>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <div class="single-footer-widget">
                            <h6 class="footer_title">Newsletter</h6>
                            <p>Stay updated with our latest trends</p>
                            <div id="mc_embed_signup">
                                <form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                                 method="get" class="subscribe_form relative">
                                    <div class="input-group d-flex flex-row">
                                        <input name="EMAIL" placeholder="Email Address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email Address '"
                                         required="" type="email">
                                        <button class="btn sub-btn">
                                            <span class="lnr lnr-arrow-right"></span>
                                        </button>
                                    </div>
                                    <div class="mt-10 info"></div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6">
                        <div class="single-footer-widget instafeed">
                            <h6 class="footer_title">Instagram Feed</h6>
                            <ul class="list instafeed d-flex flex-wrap">
                                <li>
                                    <img src="img/instagram/Image-01.jpg" alt="">
                                </li>
                                <li>
                                    <img src="img/instagram/Image-02.jpg" alt="">
                                </li>
                                <li>
                                    <img src="img/instagram/Image-03.jpg" alt="">
                                </li>
                                <li>
                                    <img src="img/instagram/Image-04.jpg" alt="">
                                </li>
                                <li>
                                    <img src="img/instagram/Image-05.jpg" alt="">
                                </li>
                                <li>
                                    <img src="img/instagram/Image-06.jpg" alt="">
                                </li>
                                <li>
                                    <img src="img/instagram/Image-07.jpg" alt="">
                                </li>
                                <li>
                                    <img src="img/instagram/Image-08.jpg" alt="">
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-2 col-md-6 col-sm-6">
                        <div class="single-footer-widget f_social_wd">
                            <h6 class="footer_title">Follow Us</h6>
                            <p>Let us be social</p>
                            <div class="f_social">
                                <a href="#">
                                    <i class="fa fa-facebook"></i>
                                </a>
                                <a href="#">
                                    <i class="fa fa-twitter"></i>
                                </a>
                                <a href="#">
                                    <i class="fa fa-instagram"></i>
                                </a>
                                <a href="#">
                                    <i class="fa fa-linkedin"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row footer-bottom d-flex justify-content-between align-items-center">
                    <p class="col-lg-12 footer-text text-center">
    Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved by <a href="#">HACKING BAD</a>
                    </p>
                </div>
            </div>
        </footer>
        <!--================ End footer Area  =================-->



        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="{% static 'crop/js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'crop/js/popper.js' %}"></script>
        <script src="{% static 'crop/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'crop/js/stellar.js' %}"></script>
        <script src="{% static 'crop/vendors/lightbox/simpleLightbox.min.js' %}"></script>
        <script src="{% static 'crop/vendors/nice-select/js/jquery.nice-select.min.js' %}"></script>
        <script src="{% static 'crop/vendors/isotope/imagesloaded.pkgd.min.js' %}"></script>
        <script src="{% static 'crop/vendors/isotope/isotope-min.js' %}"></script>
        <script src="{% static 'crop/vendors/owl-carousel/owl.carousel.min.js' %}"></script>
        <script src="{% static 'crop/js/jquery.ajaxchimp.min.js' %}"></script>
        <script src="{% static 'crop/vendors/counter-up/jquery.waypoints.min.js' %}"></script>
        <script src="{% static 'crop/vendors/flipclock/timer.js' %}"></script>
        <script src="{% static 'crop/vendors/counter-up/jquery.counterup.js' %}"></script>
        <script src="{% static 'crop/js/mail-script.js' %}"></script>
        <script src="{% static 'crop/js/theme.js' %}"></script>
    </body>

    </html>

crop/templates/crop/home.html
{% extends 'crop/base.html' %}


<!--{% block recent_posts %}

{% for post in recent_posts %}
<ul>
        
          <li class="clearfix">

            
              <div class="widget-entry-summary" style="margin: 0;">
            

              <h5 style="margin: 0;"><a href="{% url 'crop:post-detail' post.id %}">{{ post.name }}</a></h5>
              <span>{{ post.date_posted }}</span>
            </div>

          </li>
        
      </ul>
      {% endfor %}

{% endblock recent_posts %}

{% block archieves %}
{% for post in recent_posts %}
<ul>
        
          <li class="clearfix">

            
              <div class="widget-entry-summary" style="margin: 0;">
            

              <h5 style="margin: 0;"><a href="{% url 'crop:post-detail' post.id %}">{{ post.title }}</a></h5>
              <span>{{ post.date_posted }}</span>
            </div>

          </li>
        
      </ul>
      {% endfor %}

{% endblock archieves %}
-->


{% block content %}
  
  <article class="media content-section">
      <div class="media-body">
        <div class="article-metadata">
          <h2 style="font-size:40px; color: black; "><a style="color: black;" class="article-title" href="">RECENT CROPS POSTED</a></h2>
          </div></div></article>
  


  {% for post in posts %}
    <article class="media content-section">
      <div class="media-body">
        <h2 style="font-size:20px; color: black; "><a style="color: black;" class="article-title" href="{% url 'crop:post-detail' post.id %}">{{ post.name }}</a></h2>
        {% if post.image %}
        <img src="{ post.image.url }">
        {% endif %}
        <p>Quantity: {{ post.quantity }} {{ post.unit.name }}</p>
        <p>Price: Rs.{{ post.price }}</p>
        <p class="article-content content-markdown">{{ post.content }}</p>
        <div class="article-metadata">
          <a class="mr-2" style="color: black;" href="{% url 'crop:user-posts' post.farmer.username %}">{{ post.farmer }}</a> &nbsp;&nbsp;&nbsp;
          <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
        </div>
      </div>
    </article><hr>
  {% endfor %}

{% if posts.has_other_pages %}
  <ul class="pagination">
    {% if posts.has_previous %}
      <li><a href="?page={{ posts.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in posts.paginator.page_range %}
      {% if posts.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a style="color: black;" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if posts.has_next %}
      <li><a href="?page={{ posts.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
{% endblock %}

crop/templates/crop/post_archive_month.html
{% extends "crop/home.html" %}

{% block content %}

{% for da in date_list %}
<p>{{ da|date:"F" }}</p>
{% endfor %}

<ul>
    {% for article in object_list %}
        <li>{{ article.date_posted|date:"F j, Y" }}:<a href="{% url 'crop:post-detail' article.id %}"> {{ article.title }}</a></li>
    {% endfor %}
</ul>

<p>
    {% if previous_month %}
        Previous Month: {{ previous_month|date:"F Y" }}
    {% endif %}
    {% if next_month %}
        Next Month: {{ next_month|date:"F Y" }}
    {% endif %}
</p>
<br><br><br>
<br><br><br>
{% endblock content %}

crop/templates/crop/post_confirm_delete.html
{% extends "crop/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="{% url 'crop:post-delete' %}">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

crop/templates/crop/post_detail.html
{% extends "crop/base.html" %}

{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" style="width: 75px; height: 75px;" src="{{ object.author.profile.image.url }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{% url 'crop:user-posts' object.farmer.username %}">{{ object.author }}</a>
        <small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>
        {% if object.author == user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'crop:post-update' object.id %}">Update</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'crop:post-delete' object.id %}">Delete</a>
          </div>
        {% endif %}
      </div>
      <h2 style="font-size:30px" class="article-title">{{ object.title }}</h2>
      <p class="article-content content-markdown">{{ object.content }}</p>
            <p class="article-content content-markdown">{{ object.content }}</p>
     <button type="button" class="btn btn-success">
      {% if highest and bidder %}
 Highest Bid : £ {{ highest }} by {{ bidder }}</button>
{% endif %}
      {% if user.is_authenticated and now < object.date_valid %}
 <br><br><br>     <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <h5><legend class="border-bottom mb-4">BID</legend></h5>
                {{ form}}
                </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Bid</button>

      {% else %}
      {% if bidder == user.username and object.owner != user %}
      <div><br>
<form action="{% url 'core:buy' object.id %}">
  {% csrf_token %}
        <button class="btn btn-outline-dark" type="submit">Buy</button>
      </form></div>{% else %}
      <p>You must be logged in to bid or the bid has expired.</p>
      {% endif %}
      {% endif %}
</div>

    </div>

  </article>
    {% if user.is_authenticated %}
      <h3>Add comment</h3>
      <form action="." method="POST">
        {% csrf_token %}
        {{ comment_form.as_p }}
        <button class="btn btn-outline-info" type="submit">Add comment</button>
      </form>
    {% endif %}
<hr>
    {% for comment in comments %}
    <article class="media content-section">
    <div class="article-metadata">
        <a class="mr-2" href="{% url 'crop:user-posts' object.author.username %}">{{ comment.author }}</a>
        <small class="text-muted">{{ comment.created|date:"F d, Y" }}</small>
      <p class="article-content">{{ comment.body | linebreaks }}</p>
</div></article>
      {% for reply in comment.replies.all %}
      <article class="media content-section" style="margin-left: 20px;">
    <div class="article-metadata">
        <a class="mr-2" href="{% url 'crop:user-posts' object.author.username %}">{{ reply.author }}</a>
        <small class="text-muted">{{ reply.created|date:"F d, Y" }}</small>
      <p class="article-content">{{ reply.body | linebreaks }}</p>
</div></article>{% endfor %}

      {% if user.is_authenticated %}
      <div style="margin-left: 20px;">
      <h3>Reply</h3>
      
      <form action="." method="POST">
        {% csrf_token %}
        {{ comment_form.as_p }}
        <input type="hidden" name="Parent_id", value="{{ comment.id }}">
        <button class="btn btn-outline-info" type="submit">Reply</button>
      </form>
    </div>
      {% endif %}
<hr>
    {% empty %}
    <p>There are no comments...</p>
    {% endfor %}
{% endblock content %}

crop/templates/crop/post_form.html
{% extends "crop/base.html" %}
{% load crispy_forms_tags %}


{% block head %}
{{ form.media }}
{% endblock head %}


{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">crop Post</legend>
                {{ form|crispy }}
                
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock content %}

crop/templates/crop/user_posts.html
{% extends "crop/base.html" %}
{% block content %}
    <h1 style="font-size: 35px;" class="mb-3">Posts by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>







    {% for post in posts %}
    <div class="row">
      <div class="col-md-2">
        <img class="rounded-circle account-img" style="width: 50px; height: 50px;" src="{{ post.author.profile.image.url }}"></div>
        <div class="col-md-6">
    <article class="media content-section">
      <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" style="color: black;" href="{% url 'crop:user-posts' post.author.username %}">{{ post.author }}</a> &nbsp;&nbsp;&nbsp;
          <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
        </div></div></article></div>
        <h2 style="font-size:30px; color: black; "><a style="color: black;" class="article-title" href="{% url 'crop:post-detail' post.id %}">{{ post.title }}</a></h2>

            <p class="article-content">{{ post.content|safe }}</p>
            {% for tag in post.tags.all %}
        <a href="{% url 'tagged' tag.slug %}" class="mr-1 badge badge-info">#{{ tag }}</a>
      {% endfor %}
          </div>
        </article><hr>
    {% endfor %}<br>
    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}
    <br><br>
{% endblock content %}